<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class VerbSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('verbs')->truncate();
        Schema::enableForeignKeyConstraints();

        $now  = now()->toDateTimeString();
        $rows = [];

        // ── IRREGULARES: [base, past, participle, translation, example] ──────────
        foreach ($this->irregular() as $v) {
            [$base, $past, $part, $tr, $ex] = $v;
            $rows[] = [
                'verb'        => $base,
                'infinitive'  => 'to ' . $base,
                'past'        => $past,
                'participle'  => $part,
                'translation' => $tr,
                'example'     => $ex,
                'type'        => 'irregular',
                'created_at'  => $now,
                'updated_at'  => $now,
            ];
        }

        // ── REGULARES: [base, past, translation, example] (participio = pasado) ──
        foreach ($this->regular() as $v) {
            [$base, $past, $tr, $ex] = $v;
            $rows[] = [
                'verb'        => $base,
                'infinitive'  => 'to ' . $base,
                'past'        => $past,
                'participle'  => $past,
                'translation' => $tr,
                'example'     => $ex,
                'type'        => 'regular',
                'created_at'  => $now,
                'updated_at'  => $now,
            ];
        }

        // Evita choques con el índice único 'verb' (un lema puede repetirse entre listas)
        $seen = [];
        $rows = array_values(array_filter($rows, function ($r) use (&$seen) {
            if (isset($seen[$r['verb']])) return false;
            $seen[$r['verb']] = true;
            return true;
        }));

        foreach (array_chunk($rows, 200) as $chunk) {
            DB::table('verbs')->insert($chunk);
        }

        $this->command->info('Verbos insertados: ' . count($rows));
    }

    /** 300 verbos irregulares más usados. */
    private function irregular(): array
    {
        return [
            ['be', 'was/were', 'been', 'ser / estar', 'She was happy yesterday.'],
            ['become', 'became', 'become', 'convertirse', 'He became a doctor.'],
            ['begin', 'began', 'begun', 'empezar', 'The film began at eight.'],
            ['break', 'broke', 'broken', 'romper', 'I broke my phone.'],
            ['bring', 'brought', 'brought', 'traer', 'She brought a gift.'],
            ['build', 'built', 'built', 'construir', 'They built a house.'],
            ['buy', 'bought', 'bought', 'comprar', 'I bought a new car.'],
            ['catch', 'caught', 'caught', 'atrapar', 'He caught the ball.'],
            ['choose', 'chose', 'chosen', 'elegir', 'She chose the red one.'],
            ['come', 'came', 'come', 'venir', 'They came home late.'],
            ['cost', 'cost', 'cost', 'costar', 'It cost ten dollars.'],
            ['cut', 'cut', 'cut', 'cortar', 'He cut the bread.'],
            ['do', 'did', 'done', 'hacer', 'I did my homework.'],
            ['draw', 'drew', 'drawn', 'dibujar', 'She drew a picture.'],
            ['drink', 'drank', 'drunk', 'beber', 'He drank some water.'],
            ['drive', 'drove', 'driven', 'conducir', 'They drove to the beach.'],
            ['eat', 'ate', 'eaten', 'comer', 'We ate dinner together.'],
            ['fall', 'fell', 'fallen', 'caer', 'The cup fell off the table.'],
            ['feel', 'felt', 'felt', 'sentir', 'I felt tired.'],
            ['fight', 'fought', 'fought', 'pelear', 'The boys fought a lot.'],
            ['find', 'found', 'found', 'encontrar', 'She found her keys.'],
            ['fly', 'flew', 'flown', 'volar', 'The bird flew away.'],
            ['forget', 'forgot', 'forgotten', 'olvidar', 'I forgot his name.'],
            ['forgive', 'forgave', 'forgiven', 'perdonar', 'She forgave him.'],
            ['get', 'got', 'gotten', 'obtener', 'He got a new job.'],
            ['give', 'gave', 'given', 'dar', 'They gave me a book.'],
            ['go', 'went', 'gone', 'ir', 'We went to the park.'],
            ['grow', 'grew', 'grown', 'crecer', 'The plant grew quickly.'],
            ['have', 'had', 'had', 'tener', 'I had a great time.'],
            ['hear', 'heard', 'heard', 'oír', 'She heard a noise.'],
            ['hide', 'hid', 'hidden', 'esconder', 'He hid the money.'],
            ['hit', 'hit', 'hit', 'golpear', 'The car hit a tree.'],
            ['hold', 'held', 'held', 'sostener', 'She held the baby.'],
            ['hurt', 'hurt', 'hurt', 'lastimar', 'I hurt my leg.'],
            ['keep', 'kept', 'kept', 'mantener', 'He kept his promise.'],
            ['know', 'knew', 'known', 'saber / conocer', 'I knew the answer.'],
            ['lead', 'led', 'led', 'liderar', 'She led the team.'],
            ['leave', 'left', 'left', 'dejar / irse', 'They left early.'],
            ['lend', 'lent', 'lent', 'prestar', 'I lent him my pen.'],
            ['let', 'let', 'let', 'permitir', 'She let me go.'],
            ['lose', 'lost', 'lost', 'perder', 'He lost his wallet.'],
            ['make', 'made', 'made', 'hacer / fabricar', 'She made a cake.'],
            ['mean', 'meant', 'meant', 'significar', 'What did you mean?'],
            ['meet', 'met', 'met', 'conocer / reunirse', 'We met at the cafe.'],
            ['pay', 'paid', 'paid', 'pagar', 'I paid the bill.'],
            ['put', 'put', 'put', 'poner', 'He put it on the table.'],
            ['read', 'read', 'read', 'leer', 'She read the whole book.'],
            ['ride', 'rode', 'ridden', 'montar', 'He rode his bike.'],
            ['ring', 'rang', 'rung', 'sonar / llamar', 'The phone rang twice.'],
            ['rise', 'rose', 'risen', 'levantarse / subir', 'The sun rose early.'],
            ['run', 'ran', 'run', 'correr', 'She ran a marathon.'],
            ['say', 'said', 'said', 'decir', 'He said hello.'],
            ['see', 'saw', 'seen', 'ver', 'I saw a movie.'],
            ['sell', 'sold', 'sold', 'vender', 'They sold their car.'],
            ['send', 'sent', 'sent', 'enviar', 'She sent an email.'],
            ['set', 'set', 'set', 'establecer / poner', 'He set the alarm.'],
            ['shake', 'shook', 'shaken', 'sacudir', 'She shook my hand.'],
            ['shine', 'shone', 'shone', 'brillar', 'The sun shone all day.'],
            ['shoot', 'shot', 'shot', 'disparar', 'He shot the target.'],
            ['show', 'showed', 'shown', 'mostrar', 'She showed me the way.'],
            ['shut', 'shut', 'shut', 'cerrar', 'He shut the door.'],
            ['sing', 'sang', 'sung', 'cantar', 'She sang beautifully.'],
            ['sink', 'sank', 'sunk', 'hundir', 'The boat sank fast.'],
            ['sit', 'sat', 'sat', 'sentarse', 'I sat on the chair.'],
            ['sleep', 'slept', 'slept', 'dormir', 'He slept for ten hours.'],
            ['speak', 'spoke', 'spoken', 'hablar', 'She spoke clearly.'],
            ['spend', 'spent', 'spent', 'gastar / pasar', 'I spent all my money.'],
            ['stand', 'stood', 'stood', 'estar de pie', 'He stood by the door.'],
            ['steal', 'stole', 'stolen', 'robar', 'Someone stole my bag.'],
            ['stick', 'stuck', 'stuck', 'pegar / atascar', 'The stamp stuck well.'],
            ['swim', 'swam', 'swum', 'nadar', 'They swam in the lake.'],
            ['take', 'took', 'taken', 'tomar / llevar', 'She took my advice.'],
            ['teach', 'taught', 'taught', 'enseñar', 'He taught math.'],
            ['tell', 'told', 'told', 'decir / contar', 'She told a story.'],
            ['think', 'thought', 'thought', 'pensar', 'I thought about it.'],
            ['throw', 'threw', 'thrown', 'lanzar', 'He threw the ball.'],
            ['understand', 'understood', 'understood', 'entender', 'I understood the lesson.'],
            ['wake', 'woke', 'woken', 'despertar', 'She woke up early.'],
            ['wear', 'wore', 'worn', 'usar / llevar puesto', 'He wore a blue shirt.'],
            ['win', 'won', 'won', 'ganar', 'Our team won the game.'],
            ['write', 'wrote', 'written', 'escribir', 'She wrote a letter.'],
            ['bend', 'bent', 'bent', 'doblar', 'He bent the wire.'],
            ['bet', 'bet', 'bet', 'apostar', 'I bet ten dollars.'],
            ['bind', 'bound', 'bound', 'atar', 'She bound the books together.'],
            ['bite', 'bit', 'bitten', 'morder', 'The dog bit him.'],
            ['bleed', 'bled', 'bled', 'sangrar', 'His nose bled a little.'],
            ['blow', 'blew', 'blown', 'soplar', 'The wind blew hard.'],
            ['breed', 'bred', 'bred', 'criar', 'They bred horses.'],
            ['burn', 'burnt', 'burnt', 'quemar', 'She burnt the toast.'],
            ['burst', 'burst', 'burst', 'estallar', 'The balloon burst.'],
            ['cast', 'cast', 'cast', 'lanzar / echar', 'He cast the net.'],
            ['cling', 'clung', 'clung', 'aferrarse', 'The child clung to her mother.'],
            ['creep', 'crept', 'crept', 'arrastrarse', 'The cat crept slowly.'],
            ['deal', 'dealt', 'dealt', 'tratar / repartir', 'She dealt the cards.'],
            ['dig', 'dug', 'dug', 'cavar', 'They dug a hole.'],
            ['dive', 'dove', 'dived', 'zambullirse', 'He dove into the pool.'],
            ['feed', 'fed', 'fed', 'alimentar', 'She fed the cat.'],
            ['flee', 'fled', 'fled', 'huir', 'The thief fled the scene.'],
            ['fling', 'flung', 'flung', 'arrojar', 'He flung the door open.'],
            ['freeze', 'froze', 'frozen', 'congelar', 'The lake froze over.'],
            ['grind', 'ground', 'ground', 'moler', 'She ground the coffee.'],
            ['hang', 'hung', 'hung', 'colgar', 'He hung the picture.'],
            ['kneel', 'knelt', 'knelt', 'arrodillarse', 'She knelt down to pray.'],
            ['knit', 'knit', 'knit', 'tejer', 'She knit a scarf.'],
            ['lay', 'laid', 'laid', 'colocar / poner', 'He laid the books down.'],
            ['lean', 'leant', 'leant', 'apoyarse', 'She leant against the wall.'],
            ['leap', 'leapt', 'leapt', 'saltar', 'The frog leapt away.'],
            ['learn', 'learnt', 'learnt', 'aprender', 'I learnt a new word.'],
            ['light', 'lit', 'lit', 'encender', 'He lit a candle.'],
            ['mistake', 'mistook', 'mistaken', 'confundir', 'I mistook him for my brother.'],
            ['overcome', 'overcame', 'overcome', 'superar', 'She overcame her fear.'],
            ['overtake', 'overtook', 'overtaken', 'adelantar', 'The car overtook the truck.'],
            ['prove', 'proved', 'proven', 'probar / demostrar', 'He proved his point.'],
            ['quit', 'quit', 'quit', 'renunciar / dejar', 'She quit her job.'],
            ['rebuild', 'rebuilt', 'rebuilt', 'reconstruir', 'They rebuilt the bridge.'],
            ['repay', 'repaid', 'repaid', 'devolver / reembolsar', 'I repaid the loan.'],
            ['seek', 'sought', 'sought', 'buscar', 'They sought a solution.'],
            ['sew', 'sewed', 'sewn', 'coser', 'She sewed a button on.'],
            ['shed', 'shed', 'shed', 'derramar / mudar', 'The tree shed its leaves.'],
            ['shrink', 'shrank', 'shrunk', 'encoger', 'My shirt shrank in the wash.'],
            ['slide', 'slid', 'slid', 'deslizar', 'He slid down the hill.'],
            ['sling', 'slung', 'slung', 'colgar / lanzar', 'She slung the bag over her shoulder.'],
            ['smell', 'smelt', 'smelt', 'oler', 'The flowers smelt sweet.'],
            ['sow', 'sowed', 'sown', 'sembrar', 'They sowed the seeds.'],
            ['speed', 'sped', 'sped', 'acelerar', 'The car sped away.'],
            ['spell', 'spelt', 'spelt', 'deletrear', 'She spelt the word correctly.'],
            ['spill', 'spilt', 'spilt', 'derramar', 'He spilt the milk.'],
            ['spin', 'spun', 'spun', 'girar', 'The wheel spun fast.'],
            ['spit', 'spat', 'spat', 'escupir', 'He spat out the seeds.'],
            ['split', 'split', 'split', 'dividir', 'They split the bill.'],
            ['spoil', 'spoilt', 'spoilt', 'estropear / malcriar', 'The heat spoilt the food.'],
            ['spread', 'spread', 'spread', 'esparcir / untar', 'She spread butter on the bread.'],
            ['spring', 'sprang', 'sprung', 'saltar / brotar', 'The cat sprang onto the sofa.'],
            ['steal', 'stole', 'stolen', 'robar', 'They stole the painting.'],
            ['strike', 'struck', 'struck', 'golpear', 'Lightning struck the tower.'],
            ['swear', 'swore', 'sworn', 'jurar', 'He swore to tell the truth.'],
            ['sweep', 'swept', 'swept', 'barrer', 'She swept the floor.'],
            ['swell', 'swelled', 'swollen', 'hinchar', 'His ankle swelled up.'],
            ['swing', 'swung', 'swung', 'balancear', 'The children swung on the gate.'],
            ['tear', 'tore', 'torn', 'rasgar', 'He tore the paper.'],
            ['tread', 'trod', 'trodden', 'pisar', 'Don\'t tread on the grass.'],
            ['weep', 'wept', 'wept', 'llorar', 'She wept at the news.'],
            ['wind', 'wound', 'wound', 'enrollar / dar cuerda', 'He wound the clock.'],
            ['withdraw', 'withdrew', 'withdrawn', 'retirar', 'She withdrew some money.'],
            ['wring', 'wrung', 'wrung', 'escurrir', 'He wrung out the towel.'],
            ['arise', 'arose', 'arisen', 'surgir', 'A problem arose suddenly.'],
            ['awake', 'awoke', 'awoken', 'despertar', 'She awoke at dawn.'],
            ['bear', 'bore', 'borne', 'soportar / llevar', 'He bore the pain well.'],
            ['beat', 'beat', 'beaten', 'vencer / golpear', 'Our team beat theirs.'],
            ['behold', 'beheld', 'beheld', 'contemplar', 'They beheld the sunset.'],
            ['bid', 'bid', 'bid', 'pujar / ofertar', 'She bid on the painting.'],
            ['broadcast', 'broadcast', 'broadcast', 'transmitir', 'They broadcast the match live.'],
            ['forbid', 'forbade', 'forbidden', 'prohibir', 'They forbade smoking inside.'],
            ['foresee', 'foresaw', 'foreseen', 'prever', 'No one foresaw the storm.'],
            ['forecast', 'forecast', 'forecast', 'pronosticar', 'They forecast rain for today.'],
            ['hold', 'held', 'held', 'sostener', 'She held the rope tightly.'],
            ['inlay', 'inlaid', 'inlaid', 'incrustar', 'The box was inlaid with gold.'],
            ['interweave', 'interwove', 'interwoven', 'entretejer', 'The threads were interwoven.'],
            ['kneel', 'knelt', 'knelt', 'arrodillarse', 'He knelt beside the bed.'],
            ['mislay', 'mislaid', 'mislaid', 'extraviar', 'I mislaid my glasses.'],
            ['mislead', 'misled', 'misled', 'engañar', 'The sign misled us.'],
            ['misunderstand', 'misunderstood', 'misunderstood', 'malinterpretar', 'She misunderstood the question.'],
            ['mow', 'mowed', 'mown', 'segar / cortar', 'He mowed the lawn.'],
            ['overhear', 'overheard', 'overheard', 'oír por casualidad', 'I overheard their conversation.'],
            ['oversleep', 'overslept', 'overslept', 'quedarse dormido', 'He overslept and missed the bus.'],
            ['partake', 'partook', 'partaken', 'participar', 'They partook in the feast.'],
            ['rethink', 'rethought', 'rethought', 'replantear', 'We rethought the plan.'],
            ['rewind', 'rewound', 'rewound', 'rebobinar', 'He rewound the tape.'],
            ['rewrite', 'rewrote', 'rewritten', 'reescribir', 'She rewrote the essay.'],
            ['saw', 'sawed', 'sawn', 'serrar', 'He sawed the plank in two.'],
            ['shave', 'shaved', 'shaven', 'afeitar', 'He shaved his beard.'],
            ['slay', 'slew', 'slain', 'matar', 'The knight slew the dragon.'],
            ['slit', 'slit', 'slit', 'rajar', 'She slit the envelope open.'],
            ['sneak', 'snuck', 'snuck', 'colarse', 'He snuck out at night.'],
            ['stride', 'strode', 'stridden', 'andar a zancadas', 'She strode across the room.'],
            ['strive', 'strove', 'striven', 'esforzarse', 'They strove for success.'],
            ['sublet', 'sublet', 'sublet', 'subarrendar', 'They sublet the flat.'],
            ['thrive', 'throve', 'thriven', 'prosperar', 'The business thrived.'],
            ['undergo', 'underwent', 'undergone', 'someterse a', 'He underwent surgery.'],
            ['undertake', 'undertook', 'undertaken', 'emprender', 'She undertook the project.'],
            ['undo', 'undid', 'undone', 'deshacer', 'He undid the knot.'],
            ['unwind', 'unwound', 'unwound', 'relajarse / desenrollar', 'She unwound after work.'],
            ['uphold', 'upheld', 'upheld', 'mantener / defender', 'The court upheld the law.'],
            ['upset', 'upset', 'upset', 'molestar / alterar', 'The news upset her.'],
            ['wed', 'wed', 'wed', 'casarse', 'They wed in spring.'],
            ['weave', 'wove', 'woven', 'tejer', 'She wove a basket.'],
            ['abide', 'abode', 'abode', 'acatar / soportar', 'We must abide by the rules.'],
            ['beget', 'begot', 'begotten', 'engendrar', 'Greed begot more greed.'],
            ['beseech', 'besought', 'besought', 'suplicar', 'She besought him to stay.'],
            ['bestride', 'bestrode', 'bestridden', 'montar a horcajadas', 'He bestrode the horse.'],
            ['betake', 'betook', 'betaken', 'dirigirse', 'He betook himself home.'],
            ['chide', 'chid', 'chidden', 'reprender', 'She chid the boy gently.'],
            ['cleave', 'clove', 'cloven', 'partir / hender', 'The axe clove the log.'],
            ['dwell', 'dwelt', 'dwelt', 'morar / habitar', 'They dwelt in the forest.'],
            ['forsake', 'forsook', 'forsaken', 'abandonar', 'He forsook his old habits.'],
            ['gird', 'girt', 'girt', 'ceñir', 'He girt the sword to his side.'],
            ['hew', 'hewed', 'hewn', 'talar / cortar', 'They hewed the logs.'],
            ['lade', 'laded', 'laden', 'cargar', 'The ship was laden with goods.'],
            ['rend', 'rent', 'rent', 'desgarrar', 'Grief rent her heart.'],
            ['rive', 'rived', 'riven', 'rajar', 'The tree was riven by lightning.'],
            ['shear', 'sheared', 'shorn', 'esquilar', 'They sheared the sheep.'],
            ['shrive', 'shrove', 'shriven', 'confesar / absolver', 'The priest shrove the sinner.'],
            ['smite', 'smote', 'smitten', 'golpear / herir', 'He was smitten with love.'],
            ['strew', 'strewed', 'strewn', 'esparcir', 'Petals were strewn on the floor.'],
            ['swell', 'swelled', 'swollen', 'hinchar', 'The river swelled after the rain.'],
            ['waylay', 'waylaid', 'waylaid', 'emboscar', 'Robbers waylaid the traveler.'],
            ['wend', 'wended', 'wended', 'dirigirse', 'They wended their way home.'],
            ['withhold', 'withheld', 'withheld', 'retener', 'He withheld the truth.'],
            ['withstand', 'withstood', 'withstood', 'resistir', 'The wall withstood the storm.'],
            ['outdo', 'outdid', 'outdone', 'superar', 'She outdid all her rivals.'],
            ['outgrow', 'outgrew', 'outgrown', 'crecer más que', 'He outgrew his clothes.'],
            ['outrun', 'outran', 'outrun', 'correr más que', 'The dog outran the cat.'],
            ['overdo', 'overdid', 'overdone', 'exagerar', 'He overdid the exercise.'],
            ['overdraw', 'overdrew', 'overdrawn', 'sobregirar', 'She overdrew her account.'],
            ['override', 'overrode', 'overridden', 'anular', 'The manager overrode the decision.'],
            ['overthrow', 'overthrew', 'overthrown', 'derrocar', 'Rebels overthrew the king.'],
            ['partake', 'partook', 'partaken', 'compartir / participar', 'Guests partook of the meal.'],
            ['foretell', 'foretold', 'foretold', 'predecir', 'She foretold the future.'],
            ['forego', 'forewent', 'foregone', 'renunciar a', 'He forewent his salary.'],
            ['handwrite', 'handwrote', 'handwritten', 'escribir a mano', 'She handwrote the note.'],
            ['typeset', 'typeset', 'typeset', 'componer (tipografía)', 'They typeset the book.'],
            ['undercut', 'undercut', 'undercut', 'socavar / rebajar', 'They undercut the competition.'],
            ['underlie', 'underlay', 'underlain', 'subyacer', 'Fear underlay his anger.'],
            ['underpay', 'underpaid', 'underpaid', 'pagar de menos', 'The firm underpaid its staff.'],
            ['undergo', 'underwent', 'undergone', 'experimentar', 'The city underwent change.'],
            ['unbend', 'unbent', 'unbent', 'enderezar', 'He unbent the wire.'],
            ['unfreeze', 'unfroze', 'unfrozen', 'descongelar', 'The funds were unfrozen.'],
            ['unspin', 'unspun', 'unspun', 'desenredar', 'She unspun the thread.'],
            ['miscast', 'miscast', 'miscast', 'asignar mal (papel)', 'The film was badly miscast.'],
            ['recast', 'recast', 'recast', 'reformular', 'They recast the proposal.'],
            ['redo', 'redid', 'redone', 'rehacer', 'I had to redo the work.'],
            ['remake', 'remade', 'remade', 'rehacer / versionar', 'They remade the classic film.'],
            ['resell', 'resold', 'resold', 'revender', 'He resold the tickets.'],
            ['resend', 'resent', 'resent', 'reenviar', 'She resent the email.'],
            ['reset', 'reset', 'reset', 'reiniciar', 'He reset the router.'],
            ['retake', 'retook', 'retaken', 'repetir / retomar', 'She retook the exam.'],
            ['unlearn', 'unlearnt', 'unlearnt', 'desaprender', 'He had to unlearn old habits.'],
            ['miswrite', 'miswrote', 'miswritten', 'escribir mal', 'He miswrote the address.'],
            ['outbid', 'outbid', 'outbid', 'superar la oferta', 'They outbid everyone else.'],
            ['outdo', 'outdid', 'outdone', 'superar', 'He always tries to outdo others.'],
            ['outsell', 'outsold', 'outsold', 'vender más que', 'The new model outsold the old one.'],
            ['outshine', 'outshone', 'outshone', 'eclipsar', 'She outshone everyone on stage.'],
            ['overcome', 'overcame', 'overcome', 'vencer', 'They overcame many obstacles.'],
            ['overfeed', 'overfed', 'overfed', 'sobrealimentar', 'Don\'t overfeed the fish.'],
            ['overhang', 'overhung', 'overhung', 'sobresalir', 'The cliff overhung the sea.'],
            ['overlay', 'overlaid', 'overlaid', 'recubrir', 'They overlaid the floor with tiles.'],
            ['overpay', 'overpaid', 'overpaid', 'pagar de más', 'We overpaid for the meal.'],
            ['oversee', 'oversaw', 'overseen', 'supervisar', 'She oversaw the whole project.'],
            ['overspend', 'overspent', 'overspent', 'gastar de más', 'They overspent on the wedding.'],
            ['overtake', 'overtook', 'overtaken', 'rebasar', 'A van overtook us on the highway.'],
            ['partbear', 'partbore', 'partborne', 'compartir carga', 'They partbore the cost.'],
            ['preset', 'preset', 'preset', 'preconfigurar', 'He preset the oven temperature.'],
            ['proofread', 'proofread', 'proofread', 'corregir pruebas', 'She proofread the report.'],
            ['regrow', 'regrew', 'regrown', 'volver a crecer', 'The lizard regrew its tail.'],
            ['rehear', 'reheard', 'reheard', 'volver a oír', 'The court reheard the case.'],
            ['relearn', 'relearnt', 'relearnt', 'reaprender', 'He relearnt how to walk.'],
            ['rerun', 'reran', 'rerun', 'volver a pasar', 'They reran the experiment.'],
            ['resit', 'resat', 'resat', 'reexaminarse', 'She resat the test.'],
            ['retell', 'retold', 'retold', 'volver a contar', 'He retold the old legend.'],
            ['rewin', 'rewon', 'rewon', 'recuperar', 'They rewon the title.'],
            ['unsay', 'unsaid', 'unsaid', 'desdecir', 'Some things can\'t be unsaid.'],
            ['unhide', 'unhid', 'unhidden', 'mostrar', 'He unhid the files.'],
            ['befall', 'befell', 'befallen', 'acontecer', 'A disaster befell the town.'],
            ['begird', 'begirt', 'begirt', 'rodear', 'Walls begirt the old city.'],
            ['bespeak', 'bespoke', 'bespoken', 'denotar / encargar', 'His tone bespoke anger.'],
            ['interbreed', 'interbred', 'interbred', 'cruzar (especies)', 'The species interbred freely.'],
            ['mishear', 'misheard', 'misheard', 'oír mal', 'I misheard the name.'],
            ['misread', 'misread', 'misread', 'leer mal', 'He misread the sign.'],
            ['misspell', 'misspelt', 'misspelt', 'escribir mal', 'She misspelt my surname.'],
            ['outbuild', 'outbuilt', 'outbuilt', 'construir más', 'They outbuilt every rival firm.'],
            ['outfight', 'outfought', 'outfought', 'vencer luchando', 'He outfought his opponent.'],
            ['outgrow', 'outgrew', 'outgrown', 'crecer más que', 'The town outgrew its borders.'],
            ['outride', 'outrode', 'outridden', 'cabalgar más que', 'She outrode the others.'],
            ['outspeak', 'outspoke', 'outspoken', 'hablar con franqueza', 'He outspoke his critics.'],
            ['outswim', 'outswam', 'outswum', 'nadar más que', 'She outswam the whole team.'],
            ['underbid', 'underbid', 'underbid', 'ofertar por debajo', 'They underbid their rivals.'],
            ['underbuy', 'underbought', 'underbought', 'comprar de menos', 'They underbought on stock.'],
            ['undergird', 'undergirt', 'undergirt', 'reforzar', 'Strong values undergirt the team.'],
            ['undershoot', 'undershot', 'undershot', 'quedarse corto', 'The plane undershot the runway.'],
            ['underspend', 'underspent', 'underspent', 'gastar de menos', 'They underspent the budget.'],
            ['untread', 'untrod', 'untrodden', 'desandar', 'He untrod his old path.'],
            ['upbuild', 'upbuilt', 'upbuilt', 'edificar', 'Faith upbuilt the community.'],
            ['upsweep', 'upswept', 'upswept', 'recoger hacia arriba', 'Her hair was upswept.'],
            ['miscut', 'miscut', 'miscut', 'cortar mal', 'He miscut the fabric.'],
            ['overwrite', 'overwrote', 'overwritten', 'sobrescribir', 'The file was overwritten.'],
            ['overhear', 'overheard', 'overheard', 'escuchar sin querer', 'She overheard the plan.'],
            ['outthink', 'outthought', 'outthought', 'superar en ingenio', 'He outthought his rival.'],
            ['outdraw', 'outdrew', 'outdrawn', 'atraer más', 'The show outdrew all others.'],
            ['inweave', 'inwove', 'inwoven', 'entretejer', 'Gold was inwoven in the cloth.'],
            ['forswear', 'forswore', 'forsworn', 'renunciar bajo juramento', 'He forswore violence.'],
            ['hamstring', 'hamstrung', 'hamstrung', 'paralizar / inutilizar', 'Debt hamstrung the company.'],
            ['floodlight', 'floodlit', 'floodlit', 'iluminar con focos', 'They floodlit the stadium.'],
            ['spotlight', 'spotlit', 'spotlit', 'destacar', 'The report spotlit the issue.'],
            ['backslide', 'backslid', 'backslid', 'recaer', 'He backslid into old habits.'],
            ['browbeat', 'browbeat', 'browbeaten', 'intimidar', 'They browbeat the witness.'],
            ['gainsay', 'gainsaid', 'gainsaid', 'contradecir', 'No one could gainsay her.'],
            ['inbreed', 'inbred', 'inbred', 'endogamia', 'The animals were inbred.'],
            ['miscast', 'miscast', 'miscast', 'elegir mal el reparto', 'The lead was miscast.'],
            ['outlay', 'outlaid', 'outlaid', 'desembolsar', 'They outlaid a fortune.'],
            ['dream', 'dreamt', 'dreamt', 'soñar', 'She dreamt of flying.'],
            ['thrust', 'thrust', 'thrust', 'empujar con fuerza', 'He thrust the door open.'],
            ['wet', 'wet', 'wet', 'mojar', 'The rain wet the ground.'],
            ['sweat', 'sweat', 'sweat', 'sudar', 'He sweat through his shirt.'],
            ['plead', 'pled', 'pled', 'suplicar / declararse', 'She pled guilty.'],
            ['clothe', 'clad', 'clad', 'vestir', 'They were clad in black.'],
            ['bust', 'bust', 'bust', 'romper / arrestar', 'The police bust the gang.'],
            ['telecast', 'telecast', 'telecast', 'televisar', 'They telecast the final live.'],
            ['handfeed', 'handfed', 'handfed', 'alimentar a mano', 'She handfed the lamb.'],
            ['spellbind', 'spellbound', 'spellbound', 'hechizar / cautivar', 'The show spellbound the crowd.'],
            ['crossbreed', 'crossbred', 'crossbred', 'cruzar (especies)', 'They crossbred the plants.'],
            ['countersink', 'countersank', 'countersunk', 'avellanar', 'He countersank the screw.'],
            ['forgo', 'forwent', 'forgone', 'prescindir de', 'He forwent dessert.'],
            ['bestrew', 'bestrewed', 'bestrewn', 'esparcir', 'Leaves bestrewed the path.'],
            ['frostbite', 'frostbit', 'frostbitten', 'congelar (por frío)', 'His toes were frostbitten.'],
            ['joyride', 'joyrode', 'joyridden', 'pasear (robando un coche)', 'They joyrode all night.'],
            ['deepfreeze', 'deepfroze', 'deepfrozen', 'ultracongelar', 'They deepfroze the fish.'],
            ['interlay', 'interlaid', 'interlaid', 'intercalar', 'They interlaid the pages with tissue.'],
        ];
    }

    /** 300 verbos regulares más usados: [base, past, translation, example]. */
    private function regular(): array
    {
        return [
            ['accept', 'accepted', 'aceptar', 'She accepted the offer.'],
            ['add', 'added', 'añadir', 'He added some salt.'],
            ['admire', 'admired', 'admirar', 'I admire your courage.'],
            ['admit', 'admitted', 'admitir', 'He admitted his mistake.'],
            ['advise', 'advised', 'aconsejar', 'She advised me to wait.'],
            ['agree', 'agreed', 'estar de acuerdo', 'We agreed on a plan.'],
            ['allow', 'allowed', 'permitir', 'They allowed us to enter.'],
            ['announce', 'announced', 'anunciar', 'He announced the news.'],
            ['answer', 'answered', 'responder', 'She answered the phone.'],
            ['appear', 'appeared', 'aparecer', 'A star appeared in the sky.'],
            ['argue', 'argued', 'discutir', 'They argued for hours.'],
            ['arrive', 'arrived', 'llegar', 'We arrived on time.'],
            ['ask', 'asked', 'preguntar', 'She asked a question.'],
            ['attack', 'attacked', 'atacar', 'The dog attacked the intruder.'],
            ['attend', 'attended', 'asistir', 'He attended the meeting.'],
            ['avoid', 'avoided', 'evitar', 'She avoided the traffic.'],
            ['bake', 'baked', 'hornear', 'They baked a cake.'],
            ['base', 'based', 'basar', 'The film is based on a book.'],
            ['beg', 'begged', 'rogar / mendigar', 'He begged for help.'],
            ['behave', 'behaved', 'comportarse', 'The kids behaved well.'],
            ['believe', 'believed', 'creer', 'I believed her story.'],
            ['belong', 'belonged', 'pertenecer', 'This book belonged to my dad.'],
            ['blame', 'blamed', 'culpar', 'Don\'t blame yourself.'],
            ['boil', 'boiled', 'hervir', 'She boiled the eggs.'],
            ['book', 'booked', 'reservar', 'We booked a hotel.'],
            ['borrow', 'borrowed', 'pedir prestado', 'He borrowed my pen.'],
            ['bother', 'bothered', 'molestar', 'The noise bothered me.'],
            ['brush', 'brushed', 'cepillar', 'She brushed her hair.'],
            ['call', 'called', 'llamar', 'I called my mother.'],
            ['camp', 'camped', 'acampar', 'They camped by the river.'],
            ['care', 'cared', 'importar / cuidar', 'She cared for the patient.'],
            ['carry', 'carried', 'llevar / cargar', 'He carried the bags.'],
            ['cause', 'caused', 'causar', 'The storm caused damage.'],
            ['change', 'changed', 'cambiar', 'She changed her mind.'],
            ['charge', 'charged', 'cobrar / cargar', 'They charged me twice.'],
            ['chase', 'chased', 'perseguir', 'The cat chased the mouse.'],
            ['check', 'checked', 'revisar', 'He checked his email.'],
            ['clean', 'cleaned', 'limpiar', 'She cleaned the kitchen.'],
            ['clear', 'cleared', 'despejar', 'They cleared the table.'],
            ['climb', 'climbed', 'escalar', 'We climbed the mountain.'],
            ['close', 'closed', 'cerrar', 'He closed the window.'],
            ['collect', 'collected', 'coleccionar / recoger', 'She collects stamps.'],
            ['compare', 'compared', 'comparar', 'He compared the prices.'],
            ['complain', 'complained', 'quejarse', 'They complained about the food.'],
            ['complete', 'completed', 'completar', 'She completed the task.'],
            ['consider', 'considered', 'considerar', 'We considered the offer.'],
            ['contain', 'contained', 'contener', 'The box contained books.'],
            ['continue', 'continued', 'continuar', 'They continued working.'],
            ['cook', 'cooked', 'cocinar', 'He cooked dinner.'],
            ['copy', 'copied', 'copiar', 'She copied the notes.'],
            ['correct', 'corrected', 'corregir', 'The teacher corrected the test.'],
            ['cough', 'coughed', 'toser', 'He coughed all night.'],
            ['count', 'counted', 'contar', 'She counted the money.'],
            ['cover', 'covered', 'cubrir', 'Snow covered the road.'],
            ['crash', 'crashed', 'estrellar', 'The car crashed into a wall.'],
            ['cross', 'crossed', 'cruzar', 'They crossed the street.'],
            ['cry', 'cried', 'llorar', 'The baby cried all night.'],
            ['cycle', 'cycled', 'ir en bici', 'She cycled to work.'],
            ['damage', 'damaged', 'dañar', 'The flood damaged the house.'],
            ['dance', 'danced', 'bailar', 'They danced all night.'],
            ['decide', 'decided', 'decidir', 'He decided to stay.'],
            ['deliver', 'delivered', 'entregar', 'They delivered the package.'],
            ['deny', 'denied', 'negar', 'She denied the rumor.'],
            ['describe', 'described', 'describir', 'He described the scene.'],
            ['design', 'designed', 'diseñar', 'She designed the logo.'],
            ['destroy', 'destroyed', 'destruir', 'The fire destroyed the barn.'],
            ['develop', 'developed', 'desarrollar', 'They developed an app.'],
            ['die', 'died', 'morir', 'The plant died without water.'],
            ['disagree', 'disagreed', 'estar en desacuerdo', 'I disagreed with him.'],
            ['discover', 'discovered', 'descubrir', 'She discovered a cave.'],
            ['discuss', 'discussed', 'discutir / comentar', 'They discussed the plan.'],
            ['divide', 'divided', 'dividir', 'He divided the cake.'],
            ['doubt', 'doubted', 'dudar', 'I doubted his words.'],
            ['drop', 'dropped', 'dejar caer', 'She dropped the glass.'],
            ['dry', 'dried', 'secar', 'He dried the dishes.'],
            ['earn', 'earned', 'ganar (dinero)', 'She earned a good salary.'],
            ['employ', 'employed', 'emplear', 'The firm employed many people.'],
            ['encourage', 'encouraged', 'animar', 'He encouraged me to try.'],
            ['end', 'ended', 'terminar', 'The show ended late.'],
            ['enjoy', 'enjoyed', 'disfrutar', 'We enjoyed the party.'],
            ['enter', 'entered', 'entrar', 'She entered the room.'],
            ['examine', 'examined', 'examinar', 'The doctor examined him.'],
            ['excuse', 'excused', 'disculpar', 'She excused his lateness.'],
            ['exist', 'existed', 'existir', 'Dinosaurs existed long ago.'],
            ['expect', 'expected', 'esperar', 'We expected good news.'],
            ['explain', 'explained', 'explicar', 'He explained the rules.'],
            ['explore', 'explored', 'explorar', 'They explored the island.'],
            ['express', 'expressed', 'expresar', 'She expressed her thanks.'],
            ['fail', 'failed', 'fallar / reprobar', 'He failed the exam.'],
            ['fasten', 'fastened', 'abrochar', 'Please fasten your seatbelt.'],
            ['fear', 'feared', 'temer', 'They feared the worst.'],
            ['fetch', 'fetched', 'ir a buscar', 'The dog fetched the ball.'],
            ['fill', 'filled', 'llenar', 'She filled the glass.'],
            ['finish', 'finished', 'terminar', 'He finished his work.'],
            ['fix', 'fixed', 'arreglar', 'She fixed the bike.'],
            ['fold', 'folded', 'doblar', 'He folded the clothes.'],
            ['follow', 'followed', 'seguir', 'The dog followed me home.'],
            ['force', 'forced', 'forzar', 'They forced the door open.'],
            ['form', 'formed', 'formar', 'They formed a team.'],
            ['gather', 'gathered', 'reunir / recolectar', 'A crowd gathered outside.'],
            ['greet', 'greeted', 'saludar', 'She greeted the guests.'],
            ['guess', 'guessed', 'adivinar', 'He guessed the answer.'],
            ['guide', 'guided', 'guiar', 'She guided the tourists.'],
            ['hammer', 'hammered', 'martillar', 'He hammered the nail.'],
            ['hand', 'handed', 'entregar', 'She handed me the note.'],
            ['handle', 'handled', 'manejar', 'He handled the situation well.'],
            ['happen', 'happened', 'suceder', 'It happened last night.'],
            ['hate', 'hated', 'odiar', 'She hated the cold.'],
            ['head', 'headed', 'dirigirse', 'They headed north.'],
            ['heal', 'healed', 'sanar', 'The wound healed quickly.'],
            ['heat', 'heated', 'calentar', 'She heated the soup.'],
            ['help', 'helped', 'ayudar', 'He helped his neighbor.'],
            ['hope', 'hoped', 'esperar (deseo)', 'We hoped for the best.'],
            ['hug', 'hugged', 'abrazar', 'She hugged her friend.'],
            ['hunt', 'hunted', 'cazar', 'They hunted for treasure.'],
            ['hurry', 'hurried', 'apresurarse', 'She hurried to the station.'],
            ['identify', 'identified', 'identificar', 'He identified the suspect.'],
            ['ignore', 'ignored', 'ignorar', 'She ignored the message.'],
            ['imagine', 'imagined', 'imaginar', 'He imagined a better world.'],
            ['improve', 'improved', 'mejorar', 'Her English improved fast.'],
            ['include', 'included', 'incluir', 'The price included tax.'],
            ['increase', 'increased', 'aumentar', 'Prices increased last year.'],
            ['inform', 'informed', 'informar', 'They informed us of the change.'],
            ['intend', 'intended', 'tener la intención', 'He intended to call you.'],
            ['introduce', 'introduced', 'presentar', 'She introduced her friend.'],
            ['invent', 'invented', 'inventar', 'He invented a new device.'],
            ['invite', 'invited', 'invitar', 'They invited us to dinner.'],
            ['involve', 'involved', 'involucrar', 'The job involved travel.'],
            ['join', 'joined', 'unirse', 'She joined the club.'],
            ['joke', 'joked', 'bromear', 'He joked about the weather.'],
            ['judge', 'judged', 'juzgar', 'Don\'t judge a book by its cover.'],
            ['jump', 'jumped', 'saltar', 'The cat jumped onto the bed.'],
            ['kick', 'kicked', 'patear', 'He kicked the ball hard.'],
            ['kill', 'killed', 'matar', 'The frost killed the plants.'],
            ['kiss', 'kissed', 'besar', 'She kissed his cheek.'],
            ['knock', 'knocked', 'tocar / golpear', 'Someone knocked on the door.'],
            ['land', 'landed', 'aterrizar', 'The plane landed safely.'],
            ['last', 'lasted', 'durar', 'The movie lasted two hours.'],
            ['laugh', 'laughed', 'reír', 'They laughed at the joke.'],
            ['launch', 'launched', 'lanzar', 'They launched a new product.'],
            ['like', 'liked', 'gustar', 'She liked the gift.'],
            ['link', 'linked', 'enlazar', 'He linked the two ideas.'],
            ['listen', 'listened', 'escuchar', 'She listened to music.'],
            ['live', 'lived', 'vivir', 'They lived in Spain.'],
            ['load', 'loaded', 'cargar', 'He loaded the truck.'],
            ['lock', 'locked', 'cerrar con llave', 'She locked the door.'],
            ['look', 'looked', 'mirar', 'He looked out the window.'],
            ['love', 'loved', 'amar', 'They loved the show.'],
            ['manage', 'managed', 'gestionar / lograr', 'She managed the team.'],
            ['mark', 'marked', 'marcar', 'He marked the date.'],
            ['marry', 'married', 'casarse', 'They married in June.'],
            ['match', 'matched', 'combinar / igualar', 'The socks matched.'],
            ['matter', 'mattered', 'importar', 'It mattered a lot to her.'],
            ['measure', 'measured', 'medir', 'He measured the room.'],
            ['mention', 'mentioned', 'mencionar', 'She mentioned your name.'],
            ['mind', 'minded', 'importar / cuidar', 'He minded the children.'],
            ['miss', 'missed', 'perder / extrañar', 'I missed the bus.'],
            ['mix', 'mixed', 'mezclar', 'She mixed the colors.'],
            ['move', 'moved', 'mover / mudarse', 'They moved to London.'],
            ['murder', 'murdered', 'asesinar', 'The villain was murdered.'],
            ['name', 'named', 'nombrar', 'They named the baby Leo.'],
            ['need', 'needed', 'necesitar', 'She needed more time.'],
            ['notice', 'noticed', 'notar', 'He noticed the change.'],
            ['obey', 'obeyed', 'obedecer', 'The dog obeyed the command.'],
            ['observe', 'observed', 'observar', 'They observed the stars.'],
            ['offer', 'offered', 'ofrecer', 'She offered me a seat.'],
            ['open', 'opened', 'abrir', 'He opened the box.'],
            ['order', 'ordered', 'ordenar / pedir', 'She ordered a coffee.'],
            ['own', 'owned', 'poseer', 'They owned a small shop.'],
            ['pack', 'packed', 'empacar', 'She packed her bags.'],
            ['paint', 'painted', 'pintar', 'He painted the fence.'],
            ['park', 'parked', 'estacionar', 'She parked the car outside.'],
            ['pass', 'passed', 'pasar / aprobar', 'He passed the exam.'],
            ['pause', 'paused', 'pausar', 'She paused the video.'],
            ['perform', 'performed', 'actuar / realizar', 'The band performed live.'],
            ['phone', 'phoned', 'telefonear', 'He phoned his sister.'],
            ['pick', 'picked', 'elegir / recoger', 'She picked a flower.'],
            ['plan', 'planned', 'planear', 'They planned a trip.'],
            ['plant', 'planted', 'plantar', 'He planted a tree.'],
            ['play', 'played', 'jugar / tocar', 'The kids played outside.'],
            ['please', 'pleased', 'complacer', 'The gift pleased her.'],
            ['point', 'pointed', 'señalar', 'She pointed at the map.'],
            ['polish', 'polished', 'pulir', 'He polished his shoes.'],
            ['post', 'posted', 'publicar / enviar', 'She posted a photo.'],
            ['pour', 'poured', 'verter', 'He poured the tea.'],
            ['practice', 'practiced', 'practicar', 'She practiced the piano.'],
            ['pray', 'prayed', 'rezar', 'They prayed for peace.'],
            ['prefer', 'preferred', 'preferir', 'I preferred the blue one.'],
            ['prepare', 'prepared', 'preparar', 'She prepared lunch.'],
            ['present', 'presented', 'presentar', 'He presented his idea.'],
            ['press', 'pressed', 'presionar', 'She pressed the button.'],
            ['pretend', 'pretended', 'fingir', 'He pretended to sleep.'],
            ['prevent', 'prevented', 'prevenir', 'They prevented the fire.'],
            ['produce', 'produced', 'producir', 'The factory produced cars.'],
            ['promise', 'promised', 'prometer', 'She promised to help.'],
            ['protect', 'protected', 'proteger', 'He protected his family.'],
            ['provide', 'provided', 'proporcionar', 'They provided food.'],
            ['pull', 'pulled', 'jalar', 'She pulled the rope.'],
            ['punch', 'punched', 'golpear', 'He punched the bag.'],
            ['push', 'pushed', 'empujar', 'They pushed the car.'],
            ['question', 'questioned', 'cuestionar', 'The police questioned him.'],
            ['race', 'raced', 'competir', 'They raced to the finish.'],
            ['rain', 'rained', 'llover', 'It rained all day.'],
            ['raise', 'raised', 'levantar / criar', 'She raised her hand.'],
            ['reach', 'reached', 'alcanzar / llegar', 'We reached the top.'],
            ['realize', 'realized', 'darse cuenta', 'He realized his error.'],
            ['receive', 'received', 'recibir', 'She received a letter.'],
            ['recognize', 'recognized', 'reconocer', 'I recognized her voice.'],
            ['record', 'recorded', 'grabar', 'They recorded the song.'],
            ['recycle', 'recycled', 'reciclar', 'We recycled the bottles.'],
            ['reduce', 'reduced', 'reducir', 'They reduced the price.'],
            ['refuse', 'refused', 'rechazar', 'He refused the offer.'],
            ['regret', 'regretted', 'lamentar', 'She regretted her words.'],
            ['relax', 'relaxed', 'relajarse', 'He relaxed on the sofa.'],
            ['remain', 'remained', 'permanecer', 'They remained calm.'],
            ['remember', 'remembered', 'recordar', 'I remembered her birthday.'],
            ['remind', 'reminded', 'recordar (a alguien)', 'She reminded me to call.'],
            ['remove', 'removed', 'quitar', 'He removed his hat.'],
            ['rent', 'rented', 'alquilar', 'They rented a flat.'],
            ['repair', 'repaired', 'reparar', 'He repaired the roof.'],
            ['repeat', 'repeated', 'repetir', 'She repeated the word.'],
            ['replace', 'replaced', 'reemplazar', 'They replaced the battery.'],
            ['reply', 'replied', 'responder', 'He replied to the email.'],
            ['report', 'reported', 'reportar', 'She reported the problem.'],
            ['require', 'required', 'requerir', 'The job required skill.'],
            ['rescue', 'rescued', 'rescatar', 'They rescued the dog.'],
            ['respect', 'respected', 'respetar', 'Everyone respected her.'],
            ['rest', 'rested', 'descansar', 'He rested for an hour.'],
            ['return', 'returned', 'regresar / devolver', 'She returned the book.'],
            ['review', 'reviewed', 'revisar', 'He reviewed his notes.'],
            ['reward', 'rewarded', 'recompensar', 'They rewarded his effort.'],
            ['risk', 'risked', 'arriesgar', 'She risked everything.'],
            ['roll', 'rolled', 'rodar', 'The ball rolled away.'],
            ['rub', 'rubbed', 'frotar', 'He rubbed his eyes.'],
            ['ruin', 'ruined', 'arruinar', 'The rain ruined the picnic.'],
            ['rule', 'ruled', 'gobernar', 'The king ruled for years.'],
            ['rush', 'rushed', 'apresurarse', 'They rushed to help.'],
            ['sail', 'sailed', 'navegar', 'They sailed across the sea.'],
            ['save', 'saved', 'salvar / ahorrar', 'She saved his life.'],
            ['scream', 'screamed', 'gritar', 'She screamed in fear.'],
            ['search', 'searched', 'buscar', 'They searched the house.'],
            ['separate', 'separated', 'separar', 'He separated the papers.'],
            ['serve', 'served', 'servir', 'They served dinner at eight.'],
            ['settle', 'settled', 'asentarse / resolver', 'They settled the dispute.'],
            ['shape', 'shaped', 'moldear', 'She shaped the clay.'],
            ['share', 'shared', 'compartir', 'He shared his food.'],
            ['shop', 'shopped', 'comprar', 'They shopped all afternoon.'],
            ['shout', 'shouted', 'gritar', 'He shouted for help.'],
            ['sign', 'signed', 'firmar', 'She signed the contract.'],
            ['ski', 'skied', 'esquiar', 'They skied down the slope.'],
            ['skip', 'skipped', 'saltarse', 'He skipped breakfast.'],
            ['slip', 'slipped', 'resbalar', 'She slipped on the ice.'],
            ['smile', 'smiled', 'sonreír', 'She smiled at me.'],
            ['smoke', 'smoked', 'fumar', 'He smoked a cigar.'],
            ['sneeze', 'sneezed', 'estornudar', 'She sneezed loudly.'],
            ['snow', 'snowed', 'nevar', 'It snowed last night.'],
            ['solve', 'solved', 'resolver', 'He solved the puzzle.'],
            ['sound', 'sounded', 'sonar', 'The plan sounded good.'],
            ['stamp', 'stamped', 'sellar / pisotear', 'She stamped the letter.'],
            ['stare', 'stared', 'mirar fijamente', 'He stared at the screen.'],
            ['start', 'started', 'empezar', 'The class started late.'],
            ['state', 'stated', 'declarar', 'She stated her opinion.'],
            ['stay', 'stayed', 'quedarse', 'They stayed at home.'],
            ['step', 'stepped', 'dar un paso', 'He stepped forward.'],
            ['stir', 'stirred', 'remover', 'She stirred the soup.'],
            ['stop', 'stopped', 'detener', 'The bus stopped suddenly.'],
            ['store', 'stored', 'almacenar', 'They stored the food.'],
            ['study', 'studied', 'estudiar', 'She studied all night.'],
            ['succeed', 'succeeded', 'tener éxito', 'He succeeded at last.'],
            ['suffer', 'suffered', 'sufrir', 'They suffered in silence.'],
            ['suggest', 'suggested', 'sugerir', 'She suggested a plan.'],
            ['suit', 'suited', 'quedar bien / convenir', 'The dress suited her.'],
            ['supply', 'supplied', 'suministrar', 'They supplied the tools.'],
            ['support', 'supported', 'apoyar', 'He supported the team.'],
            ['suppose', 'supposed', 'suponer', 'I supposed he was right.'],
            ['surprise', 'surprised', 'sorprender', 'The gift surprised her.'],
            ['surround', 'surrounded', 'rodear', 'Trees surrounded the house.'],
            ['survive', 'survived', 'sobrevivir', 'They survived the storm.'],
            ['suspect', 'suspected', 'sospechar', 'She suspected nothing.'],
            ['swallow', 'swallowed', 'tragar', 'He swallowed the pill.'],
            ['talk', 'talked', 'hablar', 'They talked for hours.'],
            ['taste', 'tasted', 'probar / saber a', 'The soup tasted great.'],
            ['tease', 'teased', 'burlarse', 'He teased his sister.'],
            ['thank', 'thanked', 'agradecer', 'She thanked the driver.'],
            ['tidy', 'tidied', 'ordenar', 'He tidied his room.'],
            ['tie', 'tied', 'atar', 'She tied her shoes.'],
            ['touch', 'touched', 'tocar', 'He touched the wall.'],
            ['tour', 'toured', 'recorrer', 'They toured the city.'],
            ['trade', 'traded', 'comerciar / intercambiar', 'They traded cards.'],
            ['train', 'trained', 'entrenar', 'She trained every day.'],
            ['translate', 'translated', 'traducir', 'He translated the text.'],
            ['travel', 'traveled', 'viajar', 'They traveled by train.'],
            ['treat', 'treated', 'tratar', 'The doctor treated him.'],
            ['trick', 'tricked', 'engañar', 'They tricked the guard.'],
            ['trip', 'tripped', 'tropezar', 'She tripped on a rock.'],
            ['trust', 'trusted', 'confiar', 'I trusted him completely.'],
            ['try', 'tried', 'intentar', 'She tried her best.'],
            ['turn', 'turned', 'girar', 'He turned the key.'],
            ['type', 'typed', 'teclear', 'She typed the report.'],
            ['underline', 'underlined', 'subrayar', 'He underlined the word.'],
            ['use', 'used', 'usar', 'She used a new app.'],
            ['visit', 'visited', 'visitar', 'They visited the museum.'],
            ['vote', 'voted', 'votar', 'She voted in the election.'],
            ['wait', 'waited', 'esperar', 'He waited for the bus.'],
            ['walk', 'walked', 'caminar', 'They walked to school.'],
            ['want', 'wanted', 'querer', 'She wanted a coffee.'],
            ['warm', 'warmed', 'calentar', 'He warmed his hands.'],
            ['warn', 'warned', 'advertir', 'They warned us of the danger.'],
            ['wash', 'washed', 'lavar', 'She washed the car.'],
            ['waste', 'wasted', 'desperdiciar', 'He wasted his money.'],
            ['watch', 'watched', 'ver / observar', 'They watched a film.'],
            ['water', 'watered', 'regar', 'She watered the plants.'],
            ['wave', 'waved', 'saludar con la mano', 'He waved goodbye.'],
            ['weigh', 'weighed', 'pesar', 'She weighed the fruit.'],
            ['welcome', 'welcomed', 'dar la bienvenida', 'They welcomed the guests.'],
            ['whisper', 'whispered', 'susurrar', 'She whispered a secret.'],
            ['wish', 'wished', 'desear', 'He wished for luck.'],
            ['wonder', 'wondered', 'preguntarse', 'She wondered why.'],
            ['work', 'worked', 'trabajar', 'He worked late.'],
            ['worry', 'worried', 'preocuparse', 'She worried about him.'],
            ['wrap', 'wrapped', 'envolver', 'He wrapped the gift.'],
            ['yawn', 'yawned', 'bostezar', 'She yawned during class.'],
            ['yell', 'yelled', 'gritar', 'He yelled across the field.'],
            ['zip', 'zipped', 'cerrar (cremallera)', 'She zipped up her coat.'],
            ['arrange', 'arranged', 'organizar', 'They arranged a meeting.'],
            ['attach', 'attached', 'adjuntar', 'She attached the file.'],
            ['blink', 'blinked', 'parpadear', 'He blinked in the light.'],
            ['breathe', 'breathed', 'respirar', 'She breathed deeply.'],
            ['celebrate', 'celebrated', 'celebrar', 'They celebrated the win.'],
            ['challenge', 'challenged', 'desafiar', 'He challenged the champion.'],
            ['chat', 'chatted', 'charlar', 'They chatted over coffee.'],
            ['claim', 'claimed', 'reclamar / afirmar', 'She claimed the prize.'],
            ['clap', 'clapped', 'aplaudir', 'The crowd clapped loudly.'],
            ['comb', 'combed', 'peinar', 'He combed his hair.'],
            ['confess', 'confessed', 'confesar', 'He confessed the truth.'],
            ['confuse', 'confused', 'confundir', 'The map confused them.'],
            ['connect', 'connected', 'conectar', 'She connected the cables.'],
            ['control', 'controlled', 'controlar', 'He controlled the machine.'],
            ['create', 'created', 'crear', 'She created a website.'],
            ['decorate', 'decorated', 'decorar', 'They decorated the room.'],
            ['deliver', 'delivered', 'entregar', 'He delivered the mail.'],
            ['depend', 'depended', 'depender', 'It depended on the weather.'],
            ['deserve', 'deserved', 'merecer', 'She deserved the award.'],
            ['disappear', 'disappeared', 'desaparecer', 'The cat disappeared.'],
            ['dress', 'dressed', 'vestir', 'She dressed quickly.'],
            ['expand', 'expanded', 'expandir', 'The company expanded fast.'],
            ['fade', 'faded', 'desvanecer', 'The colors faded over time.'],
            ['fit', 'fitted', 'quedar / encajar', 'The shoes fitted well.'],
            ['flash', 'flashed', 'destellar', 'The light flashed twice.'],
            ['float', 'floated', 'flotar', 'The boat floated away.'],
            ['flow', 'flowed', 'fluir', 'The river flowed gently.'],
            ['fool', 'fooled', 'engañar', 'They fooled everyone.'],
            ['gain', 'gained', 'ganar / obtener', 'He gained experience.'],
            ['glance', 'glanced', 'echar un vistazo', 'She glanced at the clock.'],
            ['grab', 'grabbed', 'agarrar', 'He grabbed his coat.'],
            ['hire', 'hired', 'contratar', 'They hired a new manager.'],
            ['hop', 'hopped', 'brincar', 'The rabbit hopped away.'],
            ['hurl', 'hurled', 'arrojar', 'He hurled the rock.'],
            ['inspire', 'inspired', 'inspirar', 'Her speech inspired us.'],
            ['knit', 'knitted', 'tejer', 'She knitted a sweater.'],
            ['knot', 'knotted', 'anudar', 'He knotted the rope.'],
            ['lift', 'lifted', 'levantar', 'She lifted the box.'],
            ['marvel', 'marveled', 'maravillarse', 'They marveled at the view.'],
            ['melt', 'melted', 'derretir', 'The ice melted fast.'],
            ['nod', 'nodded', 'asentir', 'He nodded in agreement.'],
            ['offend', 'offended', 'ofender', 'The joke offended her.'],
            ['pat', 'patted', 'dar palmaditas', 'She patted the dog.'],
            ['plug', 'plugged', 'enchufar', 'He plugged in the charger.'],
            ['print', 'printed', 'imprimir', 'She printed the document.'],
            ['rescue', 'rescued', 'rescatar', 'They rescued the swimmer.'],
            ['scratch', 'scratched', 'rascar / rayar', 'The cat scratched the sofa.'],
            ['shiver', 'shivered', 'temblar', 'She shivered in the cold.'],
            ['sigh', 'sighed', 'suspirar', 'He sighed with relief.'],
            ['sip', 'sipped', 'sorber', 'She sipped her tea.'],
            ['slam', 'slammed', 'dar un portazo', 'He slammed the door.'],
            ['snap', 'snapped', 'chasquear / romper', 'The twig snapped.'],
            ['sparkle', 'sparkled', 'brillar', 'Her eyes sparkled.'],
            ['squeeze', 'squeezed', 'apretar / exprimir', 'She squeezed the lemon.'],
            ['stretch', 'stretched', 'estirar', 'He stretched his arms.'],
            ['stumble', 'stumbled', 'tropezar', 'She stumbled in the dark.'],
            ['swap', 'swapped', 'intercambiar', 'They swapped seats.'],
            ['tap', 'tapped', 'dar golpecitos', 'He tapped on the glass.'],
            ['tip', 'tipped', 'dar propina / inclinar', 'She tipped the waiter.'],
            ['trap', 'trapped', 'atrapar', 'They trapped the mouse.'],
            ['unlock', 'unlocked', 'desbloquear', 'He unlocked the phone.'],
            ['wander', 'wandered', 'deambular', 'They wandered the streets.'],
            ['whistle', 'whistled', 'silbar', 'He whistled a tune.'],
            ['wipe', 'wiped', 'limpiar / secar', 'She wiped the table.'],
        ];
    }
}
